### ISSUE TITLE
screenshots are broken in readme

### ISSUE THREAD

**Issue by marksherman** [oplS15projects/GrEP#15]
fix it asap, I'm checking websites now. I'll put yours at the end of the list.

**Comment by marksherman** [comment]
I found a working README in your gh-pages branch.

The gh-pages branch is supposed to be for the github pages website, but it appears to contain an entire working copy of your code (like master, but with images). 

As you do not appear to use the github pages feature, you should merge it all into master.

Your web page is accepted.

**Comment by emseto** [comment]
I think I fixed it? I merged everything from gh-pages to maser and deleted gh-pages, but when I checked the website we submitted (oplS15projects.github.io/GrEP), it wasn't there. So... I added gh-pages back. I'll remove our working code from that branch right now.

**Comment by marksherman** [comment]
You didn't link the site in your readme, so I was looking at your readme,
which is still broken. Now that I know about the site, it's fine.

The way github pages works is it makes a gh-pages branch in your repo. This
branch is completely different from the master, or any code branches, and
it shares no history. That branch just holds the info to drive the web
page. There's no need to also copy the code from master into it.
